### ISSUE TITLE
Can't use custom error group hashing

### ISSUE THREAD

**Issue by julia-godoy** [kaeuferportal/raygun4go#21]
Hello,

On the Raygun official documentation there is the possibility of using a [custom error grouping ](https://raygun.com/blog/custom-error-grouping/). Although, I couldn't find this feature on this Go library.

I see that on the Java and JavaScript official libs there is support for this feature. 

I'm wondering if this feature is on the backlog for the Go lib, and if it is, when it will be available. This feature is essential for our project.

Thank you in advance

**Comment by QuantumNightmare** [comment]
Thanks for the feature request. I've created a PR to add this feature to raygun4go. It's very similar to our other language providers, as it lets you provide a callback that takes both the original error, and the Raygun message payload. Both of these can be useful to use in your logic to create a custom grouping key.

The PR is currently in QA, but you can check it out here: https://github.com/MindscapeHQ/raygun4go/pull/22

The PR also includes some bug fixes I noticed when parsing the stack trace.

**Comment by julia-godoy** [comment]
Thanks for the response!

Please let me know when the PR is merged, so I can Close this issue.

**Comment by QuantumNightmare** [comment]
No worries, the PR has now been merged so that you can start using the feature. Let us know how it goes or if you have any questions about using it.

**Comment by julia-godoy** [comment]
Thank you, I will keep you updated.
